 
DROP PROCEDURE DBO.SP_VEN_CON016
GO
/*
+=================================================================================================================+'
!  Nº de !   Nº da     ! Data  da   ! Nome do         ! Descricao das Atividades                                  !
!  Ordem ! Solicitacao ! Manutencao ! Programador     !                                                           !
+========+=============+============+=================+===========================================================+'
!    1   !             !            !                 ! Seleciona as vendas de apresentações futuras			  !
+--------+-------------+------------+-----------------+-----------------------------------------------------------+
!        !             !            !                 !                                                           !
+--------+-------------+------------+-----------------+-----------------------------------------------------------+
!        !             !            !                 !                                                           !
+========+=============+============+=================+===========================================================+'
*/

CREATE PROCEDURE DBO.SP_VEN_CON016 (
	@CODSALA    SMALLINT,
	@CODPECA    SMALLINT,	
	@DATINICIO  SMALLDATETIME,
	@DATFIM	    SMALLDATETIME,
	@CANAL		VARCHAR(50)
) AS

DECLARE 
	@CODTIPBILHETE 	INT,
	@TIPBILHETE	VARCHAR(20),
	@DATMOVIMENTO 	DATETIME,
	@NOMSETOR	VARCHAR(27),
	@INDICE		INT,
	@PRECO		MONEY,
	@VLRAGREGADOS	MONEY,
	@OUTROSVALORES	MONEY,
	@CODSALAMIN SMALLINT,
	@CODSALAMAX SMALLINT
SET NOCOUNT ON 

IF @CODSALA IS NULL 
	BEGIN
		SET @CODSALAMIN = (SELECT DISTINCT MIN(CODSALA) FROM TABAPRESENTACAO)
		SET @CODSALAMAX = (SELECT DISTINCT MAX(CODSALA) FROM TABAPRESENTACAO)
	END
ELSE
	BEGIN
		SET @CODSALAMIN = 254
		SET @CODSALAMAX = 0
	END

SELECT  	
	TABAPRESENTACAO.DATAPRESENTACAO,
	TABAPRESENTACAO.HORSESSAO,
	TABCAIXA.TIPCAIXA,
	TABLUGSALA.CODTIPBILHETE,
	TABTIPBILHETE.TIPBILHETE, 
	TABLANCAMENTO.DATMOVIMENTO,
	TABSETOR.NOMSETOR,
	TABLUGSALA.INDICE,
	TABLANCAMENTO.VALPAGTO AS PRECO,
	SUM(ISNULL(TABINGRESSOAGREGADOS.VALOR,0))  AS VLRAGREGADOS,
	0 AS OUTROSVALORES,
	CI_MIDDLEWAY..MW_CANAL_VENDA.DS_CANAL_VENDA
INTO #TMP_RESUMO
FROM       
	TABLUGSALA 
	INNER JOIN 
	TABTIPBILHETE 	
		ON  TABLUGSALA.CODTIPBILHETE 	    = TABTIPBILHETE.CODTIPBILHETE 
        INNER JOIN 
	TABSALDETALHE 	
		ON  TABLUGSALA.INDICE 				= TABSALDETALHE.INDICE 
	INNER JOIN
        TABSETOR 	
		ON  TABSALDETALHE.CODSALA           = TABSETOR.CODSALA 
		AND TABSALDETALHE.CODSETOR 			= TABSETOR.CODSETOR 
	INNER JOIN
        TABAPRESENTACAO 
		ON  TABLUGSALA.CODAPRESENTACAO      = TABAPRESENTACAO.CODAPRESENTACAO 
		AND (TABAPRESENTACAO.CODSALA 	    = @CODSALA OR (TABAPRESENTACAO.CODSALA >= @CODSALAMIN AND TABAPRESENTACAO.CODSALA <= @CODSALAMAX))
		AND TABAPRESENTACAO.CODPECA 	    = @CODPECA
	INNER JOIN
	TABLANCAMENTO 
		ON  TABTIPBILHETE.CODTIPBILHETE     = TABLANCAMENTO.CODTIPBILHETE 
		AND TABSALDETALHE.INDICE            = TABLANCAMENTO.INDICE 
		AND TABAPRESENTACAO.CODAPRESENTACAO = TABLANCAMENTO.CODAPRESENTACAO
		AND TABLANCAMENTO.CODTIPLANCAMENTO  = 1
	INNER JOIN
	TABCAIXA
		ON TABCAIXA.CODCAIXA 		    = TABLANCAMENTO.CODCAIXA
	LEFT JOIN
	TABINGRESSOAGREGADOS
		ON  TABINGRESSOAGREGADOS.CODVENDA   = TABLUGSALA.CODVENDA
		AND TABINGRESSOAGREGADOS.INDICE     = TABLUGSALA.INDICE
	INNER JOIN 
	CI_MIDDLEWAY..MW_CANAL_VENDA
		ON CI_MIDDLEWAY..MW_CANAL_VENDA.ID_CANAL_VENDA = TABCAIXA.ID_CANAL_VENDA
WHERE
	(TABLUGSALA.CODVENDA IS NOT NULL) 
AND 	(CONVERT(SMALLDATETIME,CONVERT(VARCHAR(10),TABAPRESENTACAO.DATAPRESENTACAO,112) + ' ' +  TABAPRESENTACAO.HORSESSAO) >= @DATINICIO)
AND 	(CONVERT(SMALLDATETIME,CONVERT(VARCHAR(10),TABAPRESENTACAO.DATAPRESENTACAO,112) + ' ' +  TABAPRESENTACAO.HORSESSAO) <= @DATFIM OR @DATFIM IS NULL)
AND	NOT EXISTS (SELECT 1 FROM TABLANCAMENTO BB
			WHERE TABLANCAMENTO.NUMLANCAMENTO = BB.NUMLANCAMENTO
			  AND TABLANCAMENTO.CODTIPBILHETE = BB.CODTIPBILHETE
			  AND BB.CODTIPLANCAMENTO = 2
			  AND TABLANCAMENTO.CODAPRESENTACAO = BB.CODAPRESENTACAO
			  AND TABLANCAMENTO.INDICE          = BB.INDICE)
GROUP BY 
	TABAPRESENTACAO.DATAPRESENTACAO,
	TABAPRESENTACAO.HORSESSAO,
	TABCAIXA.TIPCAIXA,
	TABLUGSALA.CODTIPBILHETE,
	TABTIPBILHETE.TIPBILHETE, 
	TABLANCAMENTO.DATMOVIMENTO,
	TABSETOR.NOMSETOR,
	TABLUGSALA.INDICE,
	TABLANCAMENTO.VALPAGTO,
	CI_MIDDLEWAY..MW_CANAL_VENDA.DS_CANAL_VENDA

-- SELECT PARA COMPLEMENTO DE MEIA ENTRADA
INSERT INTO #TMP_RESUMO
SELECT  
	TABAPRESENTACAO.DATAPRESENTACAO,
	TABAPRESENTACAO.HORSESSAO,
	TABCAIXA.TIPCAIXA,
	TABLUGSALA.CODTIPBILHETECOMPLMEIA,
	TABTIPBILHETE.TIPBILHETE, 
	TABLANCAMENTO.DATMOVIMENTO,
	TABSETOR.NOMSETOR,
	TABLUGSALA.INDICE,
	TABLANCAMENTO.VALPAGTO AS PRECO,
	SUM(ISNULL(TABINGRESSOAGREGADOS.VALOR,0))  AS VLRAGREGADOS,
	0 AS OUTROSVALORES,
	CI_MIDDLEWAY..MW_CANAL_VENDA.DS_CANAL_VENDA
FROM       
	TABLUGSALA 
	INNER JOIN 
	TABTIPBILHETE 	
		ON  TABLUGSALA.CODTIPBILHETECOMPLMEIA 	    = TABTIPBILHETE.CODTIPBILHETE 
        INNER JOIN 
	TABSALDETALHE 	
		ON  TABLUGSALA.INDICE 		    = TABSALDETALHE.INDICE 
	INNER JOIN
        TABSETOR 	
		ON  TABSALDETALHE.CODSALA           = TABSETOR.CODSALA 
		AND TABSALDETALHE.CODSETOR 	    = TABSETOR.CODSETOR 
	INNER JOIN
        TABAPRESENTACAO 
		ON  TABLUGSALA.CODAPRESENTACAO      = TABAPRESENTACAO.CODAPRESENTACAO 
		AND (TABAPRESENTACAO.CODSALA 	    = @CODSALA OR (TABAPRESENTACAO.CODSALA >= @CODSALAMIN AND TABAPRESENTACAO.CODSALA <= @CODSALAMAX))
		AND TABAPRESENTACAO.CODPECA 	    = @CODPECA
	INNER JOIN
	TABLANCAMENTO 
		ON  TABTIPBILHETE.CODTIPBILHETE     = TABLANCAMENTO.CODTIPBILHETE 
		AND TABSALDETALHE.INDICE            = TABLANCAMENTO.INDICE 
		AND TABAPRESENTACAO.CODAPRESENTACAO = TABLANCAMENTO.CODAPRESENTACAO
		AND TABLANCAMENTO.CODTIPLANCAMENTO  = 4
	INNER JOIN
	TABCAIXA
		ON TABCAIXA.CODCAIXA 		    = TABLANCAMENTO.CODCAIXA
	LEFT JOIN
	TABINGRESSOAGREGADOS
		ON  TABINGRESSOAGREGADOS.CODVENDA   = TABLUGSALA.CODVENDA
		AND TABINGRESSOAGREGADOS.INDICE     = TABLUGSALA.INDICE
	INNER JOIN 
	CI_MIDDLEWAY..MW_CANAL_VENDA
		ON CI_MIDDLEWAY..MW_CANAL_VENDA.ID_CANAL_VENDA = TABCAIXA.ID_CANAL_VENDA
WHERE
	(TABLUGSALA.CODVENDA IS NOT NULL) 
AND 	(CONVERT(SMALLDATETIME,CONVERT(VARCHAR(10),TABAPRESENTACAO.DATAPRESENTACAO,112) + ' ' +  TABAPRESENTACAO.HORSESSAO) >= @DATINICIO)
AND 	(CONVERT(SMALLDATETIME,CONVERT(VARCHAR(10),TABAPRESENTACAO.DATAPRESENTACAO,112) + ' ' +  TABAPRESENTACAO.HORSESSAO) <= @DATFIM OR @DATFIM IS NULL)
AND	NOT EXISTS (SELECT 1 FROM TABLANCAMENTO BB
			WHERE TABLANCAMENTO.NUMLANCAMENTO = BB.NUMLANCAMENTO
			  AND TABLANCAMENTO.CODTIPBILHETE = BB.CODTIPBILHETE
			  AND BB.CODTIPLANCAMENTO = 2
			  AND TABLANCAMENTO.CODAPRESENTACAO = BB.CODAPRESENTACAO
			  AND TABLANCAMENTO.INDICE          = BB.INDICE)
GROUP BY 
	TABAPRESENTACAO.DATAPRESENTACAO,
	TABAPRESENTACAO.HORSESSAO,
	TABCAIXA.TIPCAIXA,
	TABLUGSALA.CODTIPBILHETECOMPLMEIA,
	TABTIPBILHETE.TIPBILHETE, 
	TABLANCAMENTO.DATMOVIMENTO,
	TABSETOR.NOMSETOR,
	TABLUGSALA.INDICE,
	TABLANCAMENTO.VALPAGTO,
	CI_MIDDLEWAY..MW_CANAL_VENDA.DS_CANAL_VENDA


DECLARE C1 CURSOR FOR
	SELECT  
		CODTIPBILHETE,
		TIPBILHETE, 
		DATMOVIMENTO,
		NOMSETOR,
		INDICE,
		PRECO,
		VLRAGREGADOS,
		OUTROSVALORES
	FROM #TMP_RESUMO


OPEN C1

FETCH NEXT FROM C1 INTO
	@CODTIPBILHETE,
	@TIPBILHETE, 
	@DATMOVIMENTO,
	@NOMSETOR,
	@INDICE,
	@PRECO,
	@VLRAGREGADOS,
	@OUTROSVALORES

WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT  
		@OUTROSVALORES = (@PRECO - @VLRAGREGADOS) * CASE TTLB.ICDEBCRE WHEN 'D' THEN (ISNULL(TTBTL.VALOR,0)/100) ELSE (ISNULL(TTBTL.VALOR,0)/100) * -1 END
	FROM
		TABTIPBILHTIPLCTO	TTBTL
	INNER JOIN
		TABTIPLANCTOBILH	TTLB
		ON  TTLB.CODTIPLCT  = TTBTL.CODTIPLCT
		AND TTLB.ICPERCVLR  = 'P'
		AND TTLB.ICUSOLCTO != 'C'
		AND TTLB.INATIVO    = 'A'
	WHERE
		TTBTL.CODTIPBILHETE = @CODTIPBILHETE
	AND	TTBTL.DTINIVIG      = (SELECT MAX(TTBTL1.DTINIVIG) 
				 FROM TABTIPBILHTIPLCTO  TTBTL1,
				      TABTIPLANCTOBILH   TTLB1
				WHERE TTBTL1.CODTIPBILHETE = TTBTL.CODTIPBILHETE
				  AND TTBTL1.CODTIPLCT     = TTBTL.CODTIPLCT
				  AND TTBTL1.DTINIVIG     <= @DATMOVIMENTO
				  AND TTBTL1.INATIVO       = 'A'
				  AND TTLB1.CODTIPLCT     = TTBTL1.CODTIPLCT
				  AND TTLB1.ICPERCVLR     = 'P'
				  AND TTLB1.ICUSOLCTO    != 'C'
				  AND TTLB1.INATIVO       = 'A')
	AND 	TTBTL.INATIVO        = 'A'


	SELECT  
		@OUTROSVALORES = @OUTROSVALORES + (CASE TTLB.ICDEBCRE WHEN 'D' THEN ISNULL(TTBTL.VALOR,0) ELSE ISNULL(TTBTL.VALOR,0) * -1 END)
	FROM
		TABTIPBILHTIPLCTO	TTBTL
	INNER JOIN
		TABTIPLANCTOBILH	TTLB
		ON  TTLB.CODTIPLCT  = TTBTL.CODTIPLCT
		AND TTLB.ICPERCVLR  = 'V'
		AND TTLB.ICUSOLCTO != 'C'
		AND TTLB.INATIVO    = 'A'
	WHERE
		TTBTL.CODTIPBILHETE = @CODTIPBILHETE
	AND	TTBTL.DTINIVIG      = (SELECT MAX(TTBTL1.DTINIVIG) 
				 FROM TABTIPBILHTIPLCTO  TTBTL1,
				      TABTIPLANCTOBILH   TTLB1
				WHERE TTBTL1.CODTIPBILHETE = TTBTL.CODTIPBILHETE
				  AND TTBTL1.CODTIPLCT     = TTBTL.CODTIPLCT
				  AND TTBTL1.DTINIVIG     <= @DATMOVIMENTO
				  AND TTBTL1.INATIVO       = 'A'
				  AND TTLB1.CODTIPLCT     = TTBTL1.CODTIPLCT
				  AND TTLB1.ICPERCVLR     = 'V'
				  AND TTLB1.ICUSOLCTO    != 'C'
				  AND TTLB1.INATIVO       = 'A')
	AND 	TTBTL.INATIVO        = 'A'


	UPDATE #TMP_RESUMO
	SET	PRECO = @PRECO - @VLRAGREGADOS + @OUTROSVALORES
	,	OUTROSVALORES = @OUTROSVALORES
	WHERE	INDICE = @INDICE
	  AND   CODTIPBILHETE = @CODTIPBILHETE
	  AND   TIPBILHETE    = @TIPBILHETE
	  AND	DATMOVIMENTO  = @DATMOVIMENTO
	  AND   NOMSETOR      = @NOMSETOR


	FETCH NEXT FROM C1 INTO
		@CODTIPBILHETE,
		@TIPBILHETE, 
		@DATMOVIMENTO,
		@NOMSETOR,
		@INDICE,
		@PRECO,
		@VLRAGREGADOS,
		@OUTROSVALORES

END

CLOSE C1
DEALLOCATE C1

SELECT
	CONVERT(VARCHAR, DATAPRESENTACAO, 112) AS DATA_APRESENTACAO,
	HORSESSAO,
	COUNT(1) AS QTDE,
	SUM(PRECO) AS PAGTO,	
	UPPER(DS_CANAL_VENDA) AS CANAL_VENDA
FROM
	#TMP_RESUMO
WHERE
	TIPBILHETE <> 'CONVITE'
	AND UPPER(DS_CANAL_VENDA) = @CANAL
GROUP BY
	CONVERT(VARCHAR, DATAPRESENTACAO, 112), 		
	HORSESSAO,
	DS_CANAL_VENDA
UNION ALL
SELECT
	CONVERT(VARCHAR, DATAPRESENTACAO, 112) AS DATA_APRESENTACAO,
	HORSESSAO,
	COUNT(1) AS QTDE,
	SUM(PRECO) AS PAGTO,	
	'CONVITE' AS CANAL_VENDA
FROM
	#TMP_RESUMO
WHERE
	TIPBILHETE = 'CONVITE'
GROUP BY
	CONVERT(VARCHAR, DATAPRESENTACAO, 112), 		
	HORSESSAO,
	DS_CANAL_VENDA
ORDER BY	
	1,2,5
	

DROP TABLE #TMP_RESUMO

SET NOCOUNT OFF