USE CI_MIDDLEWAY;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[dbo].[GetProximaDataPagamento]')
			AND type IN (N'FN',N'IF',N'TF',N'FS',N'FT')
		)
	DROP FUNCTION [dbo].[GetProximaDataPagamento]
GO

CREATE FUNCTION dbo.GetProximaDataPagamento (@DATE DATE)
RETURNS DATE
AS
BEGIN
	DECLARE @CURRENT_DAY INT,
			@DAYS_NEXT_MONTH INT;

	SET @CURRENT_DAY = DAY(@DATE);
	SET @DAYS_NEXT_MONTH = DAY(DATEADD(DD,-1,DATEADD(MM,DATEDIFF(MM,0,'20160131')+2,0)));

	RETURN CASE
		WHEN @CURRENT_DAY <= @DAYS_NEXT_MONTH THEN DATEADD(MONTH, 1, @DATE)
		ELSE DATEADD(DD,0,DATEADD(MM,DATEDIFF(MM,-1,@DATE),0)) END;
END
GO