ALTER PROCEDURE dbo.prc_cons_historico_assinatura
	@IdCliente AS INT
AS

DECLARE @DT_ATUAL SMALLDATETIME

SET NOCOUNT ON	
	
	SET @DT_ATUAL = CAST(CONVERT(VARCHAR(10), GETDATE(), 120) AS SMALLDATETIME)	
	
	SELECT 
		PR.ID_PACOTE AS ID_HISTORICO
		,E.DS_EVENTO COLLATE SQL_Latin1_General_CP1_CI_AS AS DS_PACOTE
		,ISNULL(PR.IN_ANO_TEMPORADA,0) AS ID_ANO_TEMPORADA
		,PR.ID_CADEIRA
		,ISNULL(PR.DS_LOCALIZACAO,'') COLLATE SQL_Latin1_General_CP1_CI_AS AS DS_CADEIRA
		,TA.VALPECA AS VL_PACOTE
		,TS.NOMSETOR COLLATE SQL_Latin1_General_CP1_CI_AS AS DS_SETOR			
		--,CASE WHEN (@DT_ATUAL BETWEEN P.DT_INICIO_FASE1 AND P.DT_FIM_FASE1) AND (PR.IN_STATUS_RESERVA = 'A') THEN 1 ELSE 0 END IN_RENOVAR
		--,CASE WHEN (@DT_ATUAL BETWEEN P.DT_INICIO_FASE1 AND P.DT_FIM_FASE1) AND (PR.IN_STATUS_RESERVA IN ('A')) OR (@DT_ATUAL BETWEEN P.DT_INICIO_FASE1 AND P.DT_FIM_FASE2) AND (PR.IN_STATUS_RESERVA IN ('S')) OR (@DT_ATUAL BETWEEN P.DT_INICIO_FASE3 AND P.DT_FIM_FASE3) AND (PR.IN_STATUS_RESERVA IN ('S', 'A')) THEN 1 ELSE 0 END IN_TROCAR
		--,CASE WHEN (@DT_ATUAL BETWEEN P.DT_INICIO_FASE1 AND P.DT_FIM_FASE3) AND (PR.IN_STATUS_RESERVA IN ('A','S')) THEN 1 ELSE 0 END IN_CANCELAR	
		,PR.IN_STATUS_RESERVA
		,'PACOTE' AS IN_ORIGEM
	FROM 
		MW_PACOTE_RESERVA PR
	INNER JOIN MW_PACOTE P ON P.ID_PACOTE = PR.ID_PACOTE
	INNER JOIN MW_APRESENTACAO A ON A.ID_APRESENTACAO = P.ID_APRESENTACAO
	INNER JOIN MW_EVENTO E ON E.ID_EVENTO = A.ID_EVENTO
	INNER JOIN MW_BASE B ON B.ID_BASE  = E.ID_BASE
	INNER JOIN CI_THEATRO_MUNICIPAL..TABSALDETALHE TSD ON TSD.INDICE = PR.ID_CADEIRA
	INNER JOIN CI_THEATRO_MUNICIPAL..TABSETOR TS ON TS.CODSALA = TSD.CODSALA AND TS.CODSETOR = TSD.CODSETOR
	INNER JOIN CI_THEATRO_MUNICIPAL..TABAPRESENTACAO TA ON TA.CODAPRESENTACAO = A.CODAPRESENTACAO
	WHERE
		PR.ID_CLIENTE = @IdCliente

	--UNION ALL		
	
	--SELECT 
	--	 HA.ID_HISTORICO
	--	,HA.DS_PACOTE
	--	,HA.ID_ANO_TEMPORADA
	--	,HA.ID_CADEIRA
	--	,HA.DS_CADEIRA
	--	,HA.VL_PACOTE
	--	,HA.DS_SETOR
	--	,0 AS IN_RENOVAR
	--	,0 AS IN_TROCAR
	--	,0 AS IN_CANCELAR
	--	,'' AS IN_STATUS_RESERVA
	--	,'HISTORICO' AS IN_ORIGEM
	--FROM 
	--	MW_HIST_ASSINATURA HA
	--WHERE
	--	HA.ID_CLIENTE = @IdCliente
	--ORDER BY 
	--	ID_ANO_TEMPORADA DESC, 
	--	DS_PACOTE

SET NOCOUNT OFF
