CREATE TABLE [dbo].[reserva_NumLancamento](
	[NumLancamento] [int] NOT NULL,
 CONSTRAINT [PK_reserva_NumLancamento] PRIMARY KEY CLUSTERED 
(
	[NumLancamento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]