/*
DIMENSÃO TEMPO:
ANO - TRIMESTRE - SEMESTRE - MES - QUINZENA - SEMANA - DIA
*/
/*

insert into dim_dia_semana values (1,'DOM')
insert into dim_dia_semana values (2,'SEG')
insert into dim_dia_semana values (3,'TER')
insert into dim_dia_semana values (4,'QUA')
insert into dim_dia_semana values (5,'QUI')
insert into dim_dia_semana values (6,'SEX')
insert into dim_dia_semana values (7,'SAB')
*/

--select * from DIM_MES

/*
delete dim_dia
delete dim_mes
delete dim_quinzena_mes
delete dim_trimestre
delete dim_semestre
delete dim_ano
*/

BEGIN

declare
  @DATAINICIO  	DATETIME,
  @DATAFIM		DATETIME,
  @DATA			DATETIME

-- EXECUTAR SEMPRE 1 ANO DE CADA VEZ
select @DATAINICIO  	= '20110101'
select @DATAFIM			= '20111231'

SELECT @DATA = @DATAINICIO

DECLARE @ID_SEMANA INT



	SELECT @ID_SEMANA = 1
	select @DATA = @DATAINICIO

	-- CARGA DIMENSÃO DIA

	WHILE ( @DATA <= @DATAFIM ) BEGIN

		INSERT INTO DIM_DIA (
			ID_DIA,
			DT_DIA,
			ID_DIA_ANTERIOR,
			ID_DIA_ANO_ANTERIOR,
			ID_ANO,
			ID_SEMESTRE,
			ID_TRIMESTRE,
			ID_MES,
			ID_QUINZENA_MES,
			ID_DIA_SEMANA
		) VALUES (
			CONVERT(VARCHAR,@DATA,112) , --YYYYMMDD
			@DATA, -- 'YYYY-MM-DD'
			CONVERT(VARCHAR,DATEADD (DAY, -1, @DATA),112), --DIA ANTERIOR
			CONVERT(VARCHAR,DATEADD (YEAR, -1, @DATA),112) , --DIA NO ANO ANTERIOR
			YEAR(@DATA),
            YEAR(@DATA)*10 + FLOOR((MONTH(@DATA) - 1)/6) + 1, --SEMESTRE
            YEAR(@DATA)*10 + FLOOR((MONTH(@DATA) - 1)/3) + 1, --TRIMESTRE
			CONVERT(INT,CONVERT(CHAR(4), YEAR(@DATA))+RIGHT('00' + CONVERT(VARCHAR(2), MONTH(@DATA)),2)), --ID DO MES
			SUBSTRING(CONVERT(VARCHAR(8),@DATA,112),1,6)+CASE WHEN DAY(@DATA)<16 THEN '1' ELSE '2' END, --QUINZENA
			DATEPART(w, @DATA)
		)

		IF DATEPART(W, @DATA) = 7
			SELECT @ID_SEMANA = @ID_SEMANA + 1

	 	SELECT @DATA = @DATA + 1
  	END


	-- CARGA DIMENSÃO MES

	INSERT INTO [DIM_MES]
           ([ID_MES]
           ,[DS_MES]
           ,[ID_MES_NO_ANO]
           ,[ID_MES_ANO_ANTERIOR]
           ,[ID_MES_ANTERIOR]
           ,[ID_ANO]
           ,[ID_SEMESTRE]
           ,[ID_TRIMESTRE])
		SELECT DISTINCT
			ID_MES,
			CASE RIGHT(ID_MES,2)
				WHEN '01' THEN 'JAN/'
				WHEN '02' THEN 'FEV/'
				WHEN '03' THEN 'MAR/'
				WHEN '04' THEN 'ABR/'
				WHEN '05' THEN 'MAI/'
				WHEN '06' THEN 'JUN/'
				WHEN '07' THEN 'JUL/'
				WHEN '08' THEN 'AGO/'
				WHEN '09' THEN 'SET/'
				WHEN '10' THEN 'OUT/'
				WHEN '11' THEN 'NOV/'
				WHEN '12' THEN 'DEZ/'
			END + LEFT(ID_MES,4),
			MONTH(DT_DIA), --ID_MES_NO_ANO,
			CONVERT(INT,CONVERT(CHAR(4), YEAR(DATEADD(YEAR, -1, DT_DIA)))+RIGHT('00' + CONVERT(VARCHAR(2), MONTH(DATEADD(YEAR, -1, DT_DIA))),2)), --ID_MES_ANO_ANTERIOR,
			CONVERT(INT,CONVERT(CHAR(4), YEAR(DATEADD(MONTH, -1, DT_DIA)))+RIGHT('00' + CONVERT(VARCHAR(2), MONTH(DATEADD(MONTH, -1, DT_DIA))),2)), --ID_MES_ANTERIOR,
			ID_ANO,
			ID_SEMESTRE,
			ID_TRIMESTRE
		FROM DIM_DIA
		WHERE ID_ANO = YEAR(@DATAINICIO)


	-- CARGA DIMENSÃO QUINZENA

	INSERT INTO DIM_QUINZENA_MES 
		SELECT DISTINCT
			D.ID_QUINZENA_MES,
			RIGHT(ID_QUINZENA_MES, 1) + 'ª QZ/' + M.DS_MES, --DS_QUINZENA_MES,

			CASE RIGHT(D.ID_QUINZENA_MES, 1)
				WHEN '1' THEN
					CASE CONVERT(CHAR(2), SUBSTRING(CONVERT(VARCHAR, D.ID_QUINZENA_MES),5,2)) 
						WHEN '01' THEN
							CONVERT(CHAR(4), CONVERT(INT, LEFT(ID_QUINZENA_MES,4))-1)+'122'
						ELSE
							D.ID_QUINZENA_MES - 9
					END
				ELSE
					D.ID_QUINZENA_MES - 1
			END AS ID_QUINZENA_ANTERIOR,

			D.ID_QUINZENA_MES - 1000, --ID_QUINZENA_ANO_ANTERIOR,
			D.ID_ANO,
			D.ID_SEMESTRE,
			D.ID_TRIMESTRE,
			D.ID_MES
		FROM DIM_DIA D
	INNER JOIN DIM_MES M ON M.ID_MES = D.ID_MES
	WHERE D.ID_ANO = YEAR(@DATAINICIO)

	-- CARGA DIMENSÃO SEMESTRE

	INSERT INTO DIM_SEMESTRE 
		SELECT DISTINCT
			D.ID_SEMESTRE,
			RIGHT(D.ID_SEMESTRE, 1) + 'º SEMESTRE/' + CONVERT(CHAR(4),YEAR(D.DT_DIA)), --DS_SEMESTRE,
			CASE RIGHT(D.ID_SEMESTRE, 1)
				WHEN 1 THEN
					D.ID_SEMESTRE - 9
				ELSE
					D.ID_SEMESTRE - 1
			END, --ID_SEMESTRE_ANTERIOR,
			D.ID_SEMESTRE - 10, --ID_SEMESTRE_ANO_ANTERIOR,
			D.ID_ANO
		FROM DIM_DIA D
		WHERE ID_ANO = YEAR(@DATAINICIO)

	-- CARGA DIMENSÃO TRIMESTRE

	INSERT INTO DIM_TRIMESTRE 
		SELECT DISTINCT
			D.ID_TRIMESTRE,
			RIGHT(D.ID_TRIMESTRE, 1) + 'º TRIMESTRE/' + CONVERT(CHAR(4),YEAR(D.DT_DIA)), --DS_TRIMESTRE,
			CASE RIGHT(D.ID_TRIMESTRE, 1)
				WHEN 1 THEN
					D.ID_TRIMESTRE - 7
				ELSE
					D.ID_TRIMESTRE - 1
			END, --ID_TRIMESTRE_ANTERIOR,
			D.ID_TRIMESTRE - 10, --ID_TRIMESTRE_ANO_ANTERIOR,
			D.ID_ANO,
			D.ID_SEMESTRE
		FROM DIM_DIA D
		WHERE ID_ANO = YEAR(@DATAINICIO)

	-- CARGA DIMENSÃO ANO

	INSERT INTO DIM_ANO 
		SELECT DISTINCT
	   		D.ID_ANO,
	   		D.ID_ANO,
			DATEPART(YEAR, DATEADD(YEAR, -1, D.DT_DIA))
		FROM DIM_DIA D
		WHERE ID_ANO = YEAR(@DATAINICIO)

END
