/****** Object:  Login [NT AUTHORITY\NETWORK SERVICE]    Script Date: 10/17/2013 10:59:11 ******/
CREATE LOGIN [NT AUTHORITY\NETWORK SERVICE] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO

