/****** Object:  Login [COMPREING\SQLServer2005MSSQLUser$COMPREING$MSSQLSERVER]    Script Date: 10/17/2013 10:57:22 ******/
CREATE LOGIN [COMPREING\SQLServer2005MSSQLUser$COMPREING$MSSQLSERVER] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO

