/****** Object:  Login [NT AUTHORITY\SYSTEM]    Script Date: 10/17/2013 10:59:34 ******/
CREATE LOGIN [NT AUTHORITY\SYSTEM] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO

